### ISSUE TITLE
코드 리뷰

### ISSUE THREAD

**Issue by jiji-hoon96** [nninyeong/mbti-test#10]
https://github.com/nninyeong/mbti-test/blob/1500930d4334348022ab501c06e0f5b7e7265486/src/context/userContextProvider.jsx#L38

UserContext 로 맞추어야 컨밴션이 적합해보여요

**Comment by nninyeong** [comment]
refactoring 브랜치에서 반영 완료했습니다! 나머지 피드백 주신 부분들 반영하고 한번에 main에 merge하겠습니다~!
