### ISSUE TITLE
코드리뷰

### ISSUE THREAD

**Issue by jiji-hoon96** [nninyeong/mbti-test#8]
https://github.com/nninyeong/mbti-test/blob/1500930d4334348022ab501c06e0f5b7e7265486/src/components/mbtiTest/ResultCard.jsx#L13-L17

isVisible 변수 대신 컴포넌트 early return을 사용하면 코드가 더 깔끔해집니다!

**Comment by nninyeong** [comment]
오!! 반영했습니다!! [commit](https://github.com/nninyeong/mbti-test/commit/d00c17739b7ce789a6a5f1fb8ecfd40e308a061a)
